### PR TITLE
create mentor07

### PR DESCRIPTION
**Pull request by shiningmoonshen**

### CODE REVIEW

**Comment by canoepus** [comment]
[mentor07.pdf](https://github.com/csmberkeley/csm-61a/files/10785815/mentor07.pdf)
[mentor07_meta.pdf](https://github.com/csmberkeley/csm-61a/files/10785816/mentor07_meta.pdf)
[mentor07_sol.pdf](https://github.com/csmberkeley/csm-61a/files/10785817/mentor07_sol.pdf)

**Comment by riya-si** [comment]
I liked how in the first tree question there was a tree diagram given so that the students could visualize what was happening in the problem, maybe having something similar for the second tree ADT question would be helpful.

**Comment by riya-si** [comment]
I also think that mutability (while super important) might be too much information for the students as they're already going over abstract data types and the tree abstraction, but not sure.

**Comment by riya-si** [comment]
In the mutability section, maybe adding a section that looks similar to below to emphasize the difference between the += and the + would help eliminate confusion!
>>> a = [1,2]
>>> b = a
>>> a += [3]
>>> a
[1, 2, 3]
>>> b
[1, 2, 3]
>>> a = a + [3]
>>> a
[1, 2, 3, 3]
>>> b
[1, 2, 3]

**Pull request merged**
