### PR TITLE
mentor08 draft

### PR DESCRIPTION
**Pull request by canoepus**

### CODE REVIEW

**Comment by canoepus** [comment]
makefile pain.
[mentor08_meta.pdf](https://github.com/csmberkeley/csm-61a/files/10837518/mentor08_meta.pdf)
[mentor08_sol.pdf](https://github.com/csmberkeley/csm-61a/files/10837519/mentor08_sol.pdf)
[mentor08.pdf](https://github.com/csmberkeley/csm-61a/files/10837517/mentor08.pdf)

**Review by Refangs — COMMENTED** [review]
Accumulate formatting issue: the blank line right below the for is indented once too much
Accumulate minor error: missing return statement
Accumulate potential clarification: Add a line to the problem statement saying what accumulate returns (currently it doesn't say what it returns, you have to look at the doctests to see that it returns the sum of everything in the list)
Accumulate: I did the problem without using the line right below the for, so maybe say that you may not need all lines

Iterators and Generators explanation minor error: it says that map and filter return an iterable, I think it was meant to say iterators instead since map and filter return iterators (you can keep calling next on a map or filter object until you get a stop iteration error)

Iterators and Generator problem 2 typo: in the line `a = iter(filter(lambda x: x \% 2, map(lambda x: x - 1, range(10))))` I think \\% is meant to just be %

Time taken (roughly):
Mutabililty WWPD: 6 mins
Environment Diagram: 11 mins
Accumulate: 11 mins
SkipMachine: 13 mins
foo: 8 mins
in_order: 2 mins
all_sums: 5 mins

Discrepancy between blank worksheet and solutions: there is a table of list methods and info in the solution but not the blank worksheet, not sure if it was intended for it to only be on the solutions

I like the problems on the worksheet, they all felt pretty instructive. SkipMachine was cool.

**Comment by riya-si** [comment]
maybe having a iterator/generator problem which is solely about iterators to gently introduce the students to programming with iterators would be helpful. 
I really like the table on page 5 and think it'll be helpful for the students to see all the different functions related to lists

**Comment by canoepus** [comment]
implemented changes!!! :heart_hands: sadly we're running a bit short on time so we can't make a pure iterator problem (the existing ones are OOP), but maybe that's soemthing we'll bring up to review session resources taskforce to include!!! or we can include building an iterator class in next WS ;D ty all for reviewing!!!

**Pull request merged**
