### PR TITLE
mentor04

### PR DESCRIPTION
**Pull request by bryanvent24**
Hi everyone! 😊

I’ve attached the latest version of the Mentor04 worksheet, along with the solutions and meta information:

[mentor04_meta.pdf](https://github.com/user-attachments/files/16925641/mentor04_meta.pdf)
[mentor04_sol.pdf](https://github.com/user-attachments/files/16925642/mentor04_sol.pdf)
[mentor04.pdf](https://github.com/user-attachments/files/16925643/mentor04.pdf)

Please take a moment to review these by EOD on 9/13. The instructions for the review process can be found [here](https://github.com/csmberkeley/csm-61a/wiki/Worksheet-review) If you can, please assign yourself to the reviewers list. If you don’t have the permissions to do so, just let me know, and I’ll make sure to get you added and fix your access.

Thanks so much for your help! I really appreciate your time and feedback. 🌟

### CODE REVIEW

**Review by Mehul-Jaiswal — APPROVED** [review]
## Approximately how long did each problem take you? (The relative length is what we care about here, I don't care how fast you actually are.)
Q1: 5mins
Q2: 3mins
Q3:  6 mins
Q2: 3 mins 
Q4: 1 min
Q5: 3 mins
## Minor errors: Are there any formatting issues or typos? Is there sufficient space for solutions and scratch work? Are answer blanks long enough? Does anything look weird? 
Everything looks good

## Problematic problems: Were there any problem statements/explanations that could use clarification or simplification? Any wrong doctests, skeletons, or solutions? Was anything even a bit confusing? 
Did not find anything specific.

## Worksheet design: Did the problems work well together? Is the number of problems acceptable? Was there a variety of difficulty levels available? Were the problems listed in order of difficulty? 
Starts with some higher level questions on HOF and ends on easy recursion problems to help students get a intro to it.

## What were the best and worst problems on the worksheet? (Why?)
Best: Env Diagram Q4, 5, Good intro to Recursion
Worst: HOF Q3, Might get confusing at some blanks

## Anything else? 
lgtm

**Comment by jimfangx** [comment]
Thank you!!

**Review by carolynwangjy — APPROVED** [review]
## Approximately how long did each problem take you? (The relative length is what we care about here, I don't care how fast you actually are.)
here's my breakdown (all in min:sec format):
HOF Q1: 7:45
HOF Q2: 8:50
HOF Q3: this q was perpetually difficult to understand
Recursion Q4: 0:30
Recursion Q5: 1:00

## Minor errors: Are there any formatting issues or typos? Is there sufficient space for solutions and scratch work? Are answer blanks long enough? Does anything look weird? 
Everything looks good here.

## Problematic problems: Were there any problem statements/explanations that could use clarification or simplification? Any wrong doctests, skeletons, or solutions? Was anything even a bit confusing? 
HOF Q3 was very confusing (even when looking through the meta.) The backslash is also syntax students haven't seen before. I think there are better problems that illustrate the idea of HOFs, and would probably suggest mentors to go through Q1/Q2 and skip Q3.

## Worksheet design: Did the problems work well together? Is the number of problems acceptable? Was there a variety of difficulty levels available? Were the problems listed in order of difficulty? 
Recursion problems were probably a bit too easy (Q4 did a good job of illustrating importance of base case and reducing the problem size, but would've liked to see one more recursion problem after Q5.)

## What were the best and worst problems on the worksheet? (Why?)
Q1/2 were the best. Q3 was the worst (see reasons in previous explanations.)

## Anything else? 
Nope!! :)

**Review by ax-md — APPROVED** [review]
## Approximately how long did each problem take you? (The relative length is what we care about here, I don't care how fast you actually are.)
Q1: 6 mins
Q2: 6 mins
Q3: 10 mins
Q4: 2 min
Q5: 2 min

## Minor errors: Are there any formatting issues or typos? Is there sufficient space for solutions and scratch work? Are answer blanks long enough? Does anything look weird? 
Looks all good to me.

## Problematic problems: Were there any problem statements/explanations that could use clarification or simplification? Any wrong doctests, skeletons, or solutions? Was anything even a bit confusing? 
I think Q3 (compound) is a little complex, but mentors can always leave it as practice for their students or cover it if their section tends to move quickly.

## Worksheet design: Did the problems work well together? Is the number of problems acceptable? Was there a variety of difficulty levels available? Were the problems listed in order of difficulty? 
Worksheet design is fantastic! It would be nice to have a very basic example of a recursive function (e.g. counting), labeled with the three steps listed conceptually.

## What were the best and worst problems on the worksheet? (Why?)
IMO the best problems are Q4 and 5 since they're a great gentle introduction to recursion. On the other hand, Q3 is a little complex, as I mentioned earlier, but it should still be included for the reasons I listed previously!

## (Highly optional) What might be a good problem to include on this sheet? 

## Anything else?

**Review by susanna-at — COMMENTED** [review]
## Approximately how long did each problem take you? (The relative length is what we care about here, I don't care how fast you actually are.)
here's my breakdown (all in min:sec format):
Q1: 7min
Q2: 6min
Q3: 10 min
Q4: 2min
Q5: 2min
## Minor errors: Are there any formatting issues or typos? Is there sufficient space for solutions and scratch work? Are answer blanks long enough? Does anything look weird? 
First two problems need much more space

## Problematic problems: Were there any problem statements/explanations that could use clarification or simplification? Any wrong doctests, skeletons, or solutions? Was anything even a bit confusing? 

Instructions were clear and right!

## Worksheet design: Did the problems work well together? Is the number of problems acceptable? Was there a variety of difficulty levels available? Were the problems listed in order of difficulty? 
Good variety of problems, I think the number of problems is more than realistically possible during a section as 1 environment diagram + the mini lecture on recursion already will take a lot of time, but it's good to have them for later practice. 

## What were the best and worst problems on the worksheet? (Why?)
Honestly the 3rd problem seems overly confusing and will probably take up a lot of time to explain, I also don't think that's really typical of exams and it touches upon recursion which is explained after, everything else is great

## Anything else? 
Great worksheet overall!

**Comment by jimfangx** [comment]
@bryanvent24 consider adding space to first two problems

**Comment by bryanvent24** [comment]
> @bryanvent24 consider adding space to first two problems

I noted on the meta one that page 5 had been left blank intentionally for students to work on any problems.

**Pull request merged**
