### PR TITLE
[fa22] mentor05

### PR DESCRIPTION
**Pull request by gabeclasson**

### CODE REVIEW

**Comment by gabeclasson** [comment]
Ready for review. 

[mentor05_meta.pdf](https://github.com/csmberkeley/csm-61a/files/9541485/mentor05_meta.pdf)
[mentor05_sol.pdf](https://github.com/csmberkeley/csm-61a/files/9541486/mentor05_sol.pdf)
[mentor05.pdf](https://github.com/csmberkeley/csm-61a/files/9541487/mentor05.pdf)

**Review by irenejy — APPROVED** [review]
## Approximately how long did each problem take you? 
Q1: 3 min
Q2: 5 min
Q3: 5 min
Q4: 4 min
Q5: 4 min
Q6: 7 min

## Minor errors: Are there any formatting issues or typos? Is there sufficient space for solutions and scratch work? Are answer blanks long enough? Does anything look weird? 
Q1: there's a colon after the first return statement
Q2: maybe a little more space if people want to draw out the call diagram? 
no other comments

## Problematic problems: Were there any problem statements/explanations that could use clarification or simplification? Any wrong doctests, skeletons, or solutions? Was anything even a bit confusing? 
Q3: The sentence about there being no restrictions on how many donuts of each flavor kind of threw me off... I'm not quite sure which part of it was confusing, and I was still able to figure out the choice of either using a flavor or not, which still led me to the right solution. 

## Worksheet design: Did the problems work well together? Is the number of problems acceptable? Was there a variety of difficulty levels available? Were the problems listed in order of difficulty? 
Overall the problems worked well together! This worksheet looks a bit long but not to the point where it's concerning. I liked the variety of difficulty in the problems, and the order looks good. 

## What were the best and worst problems on the worksheet? (Why?)
I thought Q2 was pretty interesting - it's something we usually go over anyways, but it's my first time seeing it on a CSM worksheet, so I'm glad it was added. I think students might have a harder time with Q6, with the `min` function playing into the solution, but it'll definitely be good practice. 

## (Highly optional) What might be a good problem to include on this sheet? 

## Anything else?

**Review by adit-bala — APPROVED** [review]
Once we add some space for `Q2`, should be finalized!

**Comment by gabeclasson** [comment]
Final PDFs

[mentor05_sol.pdf](https://github.com/csmberkeley/csm-61a/files/9544414/mentor05_sol.pdf)
[mentor05.pdf](https://github.com/csmberkeley/csm-61a/files/9544412/mentor05.pdf)
[mentor05_meta.pdf](https://github.com/csmberkeley/csm-61a/files/9544413/mentor05_meta.pdf)

**Pull request merged**
