### PR TITLE
fa24/mentor03

### PR DESCRIPTION
**Pull request by jimfangx**
Mentor03 is ready to review! 🚂🚂🚂 We are on schedule!

[mentor03_meta.pdf](https://github.com/user-attachments/files/16823735/mentor03_meta.pdf)
[mentor03_sol.pdf](https://github.com/user-attachments/files/16823736/mentor03_sol.pdf)
[mentor03.pdf](https://github.com/user-attachments/files/16823737/mentor03.pdf)

Review should be done by 9/6 EOD. Instructions for review is [here](https://github.com/csmberkeley/csm-61a/wiki/Worksheet-review). 

Assign yourself to the reviewers list if possible to take the ticket, if you don't have permissions lmk and I'll assign you + fix your perms.

Edit:
New PR hopefully with fixed branch protection rules

### CODE REVIEW

**Review by Mehul-Jaiswal — APPROVED** [review]
## Approximately how long did each problem take you? (The relative length is what we care about here, I don't care how fast you actually are.)
Env Diagrams Q1: 3mins
Env Diagrams Q2: 3mins
HOF Q1:  5 mins
HOF Q2: 3 mins 
HOF Q3: 4 mins 
HOF Q4: 2 mins 
HOF Q5: 2 mins 
## Minor errors: Are there any formatting issues or typos? Is there sufficient space for solutions and scratch work? Are answer blanks long enough? Does anything look weird? 
Nope, Looks good.

## Problematic problems: Were there any problem statements/explanations that could use clarification or simplification? Any wrong doctests, skeletons, or solutions? Was anything even a bit confusing? 
Looks good, pretty much accurate.

## Worksheet design: Did the problems work well together? Is the number of problems acceptable? Was there a variety of difficulty levels available? Were the problems listed in order of difficulty? 
Yes, starts with easy goes towards medium level questions

## What were the best and worst problems on the worksheet? (Why?)
Best: Env Diagram Q2, Good question to get familiar with the env
Worst: HOF Q2, sometimes students might get confused but good question for exam practice

## Anything else? 
lgtm

**Comment by jimfangx** [comment]
Thanks for the review!

**Comment by jimfangx** [comment]
actually timing looks pretty ok - lets merge then! thanks for the review again!

**Review by carolynwangjy — COMMENTED** [review]
this is past the mentor03 release date, but I just wanted to add some comments for future reference anyways!

## Approximately how long did each problem take you? (The relative length is what we care about here, I don't care how fast you actually are.)
here's my breakdown (all in min:sec format):
Env Diagrams Q1: 4:40
Env Diagrams Q2: 6:11
HOF Q1: 4:12
HOF Q2: 0:53
HOF Q3: 2:21
HOF Q4: 1:12
HOF Q5: 1:02
## Minor errors: Are there any formatting issues or typos? Is there sufficient space for solutions and scratch work? Are answer blanks long enough? Does anything look weird? 
HOF Q1 definitely needs more space, while HOF Q2 doesn't need very much. In the future, it might be worth moving HOF Q2 lower so there's more space to draw the environment diagram in Q1.

## Problematic problems: Were there any problem statements/explanations that could use clarification or simplification? Any wrong doctests, skeletons, or solutions? Was anything even a bit confusing? 
Everything was very clear!

## Worksheet design: Did the problems work well together? Is the number of problems acceptable? Was there a variety of difficulty levels available? Were the problems listed in order of difficulty? 
Yes, problems were great! Good for mentors to pick and choose from :)

## What were the best and worst problems on the worksheet? (Why?)
Absolutely love the first two; they clarify a lot of conceptual things. no problems are inherently bad, but problem 4 is probably the least helpful.

## (Highly optional) What might be a good problem to include on this sheet? 

## Anything else? y'alls are doing a great job :)

**Pull request merged**
