### PR TITLE
fa24/mentor05 + new problems

### PR DESCRIPTION
**Pull request by jimfangx**
Mentor05 is complete!

I have stepped up the difficulty since we got feedback that worksheets have been too easy. Let me know if this is too much.

Note about reviews: I'll request all of yall to review on github but **only one person needs to review!** - putting everyone on the list of reviewers gives anyone the ability to file a review, otherwise yall won't have permissions.

Added new problems to the bank:
* recursion/hard: near.tex
* recursion/medium: fast_modular_exponentiation.tex

Update:
Realized a version of fast modular exponentiation existed already under the growth folder (more focused on runtime) after making the worksheet... :(  - will take care of merging both soon
- [ ] Merge both modular exponentiation problems
- [ ] we should make a directory of problems to address this so it doesnt happen again

[mentor05_meta.pdf](https://github.com/user-attachments/files/17004715/mentor05_meta.pdf)
[mentor05_sol.pdf](https://github.com/user-attachments/files/17004716/mentor05_sol.pdf)
[mentor05.pdf](https://github.com/user-attachments/files/17004717/mentor05.pdf)

### CODE REVIEW

**Comment by jimfangx** [comment]
Update: added overview

**Comment by carolynwangjy** [comment]
## Approximately how long did each problem take you? (The relative length is what we care about here, I don't care how fast you actually are.)
- Q1 fizzbuzz (recursion) - 2:40
- Q2 sum_prime_digits (recursion) - 5:04 (took longer bc i was testing an alt solution that also works)
- Q3 near (recursion) - took embarrassingly long lol. this was one of the harder ones added, and it's conceptually difficult, since how we're modifying the input in the recursion is we're working backwards and checking whether the last digit is greater than the ones before it (using smallest as a tracker), even though the problem introduces the problem as needing an element i to be smaller than elements i + 2, i + 3. so the overall implementation logic is backwards compare to how the problem is introduced. and since the parameters smallest and d are not givens, it's quite difficult to figure out how to approach the problem. i would say this one was a tad bit difficult
- Q4 has_sum (tree recursion) - 2 min
- Q5 mario (tree recursion) - 3 min
- Q6 - fast modular exponentiation - 5 min (good ex of tree recursion / divide and conquer, but most 61a students haven't taken cs70 yet, so the idea of modulo might be a bit confusing. i.e. 12 = 2 (mod 5) or properties of mods (distributing exponents) is something they haven't encountered yet, so why we need to, i.e., do half_power * half_power % modulus again after doing the recursive call for half_power could not be as intuitive to most students.) i would say that this problem is a good one to mark as "optional" if any mentors have students who want more of a conceptual challenge, but it might not be super illustrative during normal practice

## Minor errors: Are there any formatting issues or typos? Is there sufficient space for solutions and scratch work? Are answer blanks long enough? Does anything look weird? 
- the input for the last doctest in recursion Q3 (near) is incorrect. based on the past exam vid, it should be 
`>>> near(812348567)`, rather than `>>> near(14735476)`

## Problematic problems: Were there any problem statements/explanations that could use clarification or simplification? Any wrong doctests, skeletons, or solutions? Was anything even a bit confusing? 
Q3 was hard to grasp conceptually. the walkthrough helped, but i think this one might be a bit too difficult as a harder recursion problem)

## Worksheet design: Did the problems work well together? Is the number of problems acceptable? Was there a variety of difficulty levels available? Were the problems listed in order of difficulty? 

## What were the best and worst problems on the worksheet? (Why?)
Best: mario (all time fav), sum_prime_digits, fizzbuzz, fast_modular_exponentiation (given students already have a grasp of modulus, which depends on the student)

Worst: near (conceptually hard to understand what to do once the recursive leap of faith works)

## (Highly optional) What might be a good problem to include on this sheet? 

## Anything else? @jimfangx after you pushed the meta with the explanation added back in and the minor typo fixed, i couldn't find the most recently-revised worksheet, so this is based on the first pull request you sent us (the ws without the meta explanation in the beginning)
as a side note, I talked to my JMs yesterday (two of them teach NPE sections) and most of them said the current difficulty was fine. i think it was the right choice to remove gibonacci (that doesn't really add much value since it's basically fib with one more recursive call), but it seems like general feedback is overall difficulty of all the worksheets is more or less okay atm!

**Review by carolynwangjy — APPROVED** [review]
## Approximately how long did each problem take you? (The relative length is what we care about here, I don't care how fast you actually are.)
- Q1 fizzbuzz (recursion) - 2:40
- Q2 sum_prime_digits (recursion) - 5:04 (took longer bc i was testing an alt solution that also works)
- Q3 near (recursion) - took embarrassingly long lol. this was one of the harder ones added, and it's conceptually difficult, since how we're modifying the input in the recursion is we're working backwards and checking whether the last digit is greater than the ones before it (using smallest as a tracker), even though the problem introduces the problem as needing an element i to be smaller than elements i + 2, i + 3. so the overall implementation logic is backwards compare to how the problem is introduced. and since the parameters smallest and d are not givens, it's quite difficult to figure out how to approach the problem. i would say this one was a tad bit difficult
- Q4 has_sum (tree recursion) - 2 min
- Q5 mario (tree recursion) - 3 min
- Q6 - fast modular exponentiation - 5 min (good ex of tree recursion / divide and conquer, but most 61a students haven't taken cs70 yet, so the idea of modulo might be a bit confusing. i.e. 12 = 2 (mod 5) or properties of mods (distributing exponents) is something they haven't encountered yet, so why we need to, i.e., do half_power * half_power % modulus again after doing the recursive call for half_power could not be as intuitive to most students.) i would say that this problem is a good one to mark as "optional" if any mentors have students who want more of a conceptual challenge, but it might not be super illustrative during normal practice

## Minor errors: Are there any formatting issues or typos? Is there sufficient space for solutions and scratch work? Are answer blanks long enough? Does anything look weird? 
- the input for the last doctest in recursion Q3 (near) is incorrect. based on the past exam vid, it should be 
`>>> near(812348567)`, rather than `>>> near(14735476)`

## Problematic problems: Were there any problem statements/explanations that could use clarification or simplification? Any wrong doctests, skeletons, or solutions? Was anything even a bit confusing? 
Q3 was hard to grasp conceptually. the walkthrough helped, but i think this one might be a bit too difficult as a harder recursion problem)

## Worksheet design: Did the problems work well together? Is the number of problems acceptable? Was there a variety of difficulty levels available? Were the problems listed in order of difficulty? 

## What were the best and worst problems on the worksheet? (Why?)
best: mario (all time fav), sum_prime_digits, fizzbuzz, fast_modular_exponentiation (given students already have a grasp of modulus, which depends on the student)

worst: near (conceptually hard to understand what to do once the recursive leap of faith works)

## Anything else? 
- @jimfangx after you pushed the meta with the explanation added back in and the minor typo fixed, i couldn't find the most recently-revised worksheet, so this is based on the first pull request you sent us (the ws without the meta explanation in the beginning)
- as a side note, I talked to my JMs yesterday (two of them teach NPE sections) and most of them said the current difficulty was fine. i think it was the right choice to remove gibonacci (that doesn't really add much value since it's basically fib with one more recursive call), but it seems like general feedback is that the overall difficulty of all the worksheets is more or less okay atm!

**Comment by jimfangx** [comment]
Thanks for the review! check slack we'll cordinate an edit there

**Comment by jimfangx** [comment]
changes added! Ready to merge!

**Pull request merged**
